create database dbElectrodomestico;

use dbElectrodomestico

--TABLE CLIENTE
create table CLIENTE (
CODCLI	char (4) NOT NULL,
NOMCLI	varchar(60) NOT NULL,
APECLI	varchar(80) NOT NULL,
EMACLI	varchar(80) NOT NULL,
CELCLI	char(9) NOT NULL,
DIRCLI	varchar(70) NOT NULL,
ESTCLI	char(1) NOT NULL,
);

INSERT INTO CLIENTE (CODCLI, NOMCLI,APECLI,EMACLI,CELCLI,DIRCLI,ESTCLI)
VALUES   ('CL01','Juana','Campos Ortis','juana.campos@hmail.com','987485152','AV.Miraflores','A');
			
SELECT * FROM CLIENTE;

--TABLE VENDEDOR
create table VENDEDOR (
CODVEND	char	(4) NOT NULL,
NOMVEND	varchar	(60) NOT NULL,
APEVEND	varchar	(80) NOT NULL,
EMAVEND	varchar	(80) NOT NULL,
CELVEND	char	(9) NOT NULL,
DIRVEND	varchar	(70) NOT NULL,
ESTVEND	char	(1) NOT NULL,
);

INSERT INTO VENDEDOR (CODVEND,NOMVEND,APEVEND,EMAVEND,CELVEND, DIRVEND, ESTVEND)
VALUES ('VEN1','Gloria','Carrizales Paredes','gloria.carrizales@gmail.com','984574123','CALLE LAS BEGONIAS','A');

--TABLE PRODUCTO
create table PRODUCTO(
CODPRO	varchar	(5) NOT NULL,
DESCPRO	varchar	(80) NOT NULL,
CATPRO	char	(1) NOT NULL,
PREPRO	decimal	(8,2) NOT NULL,
STOCKPRO int	NOT NULL,
ESTPRO	char	(1) NOT NULL,
);

INSERT INTO PRODUCTO (CODPRO, DESCPRO, CATPRO, PREPRO, STOCKPRO, ESTPRO)
VALUES ('PRO01','Refrigeradora','1','4149','15', 'A');

--TABLE PROVEEDOR
create table PROVEEDOR (
CODPROV		varchar	(5) NOT NULL,
DESCPROV	varchar	(80) NOT NULL,
CATPROV		char	(1) NOT NULL,
PREPROV		decimal	(8,2) NOT NULL,
STOCKPROV	int		NOT NULL,
ESTPROV		char	(1) NOT NULL,
);

INSERT INTO(CODPROV,DESCPROV,CATPRO,PREPROV,STOCKPROV,ESTPROV)
VALUES ('PRV01','LG Corporation','','','','A');

--TABLE VENTA
create table VENTA (
CODVEN	char	(5) NOT NULL,
FECVENT	datetime datetime ,
CODCLI	char	(4) NOT NULL,
CODVEND	char	(4) NOT NULL,
ESTVEN	char	(1) NOT NULL,
);

--TABLE VENTADETALLE
create table VENTADETALLE (
IDVENDET int IDENTITY(1, 1) NOT NULL,
CODVEN	 char(5) NOT NULL,
CODPRO	 char(5) NOT NULL,
CANPRO	 int NOT NULL,
);

--TABLE COMPRA
create table COMPRA (
CODCOM	char(5)NOT NULL,
FECCOM	datetime NOT NULL,
CODVEND	char(4) NOT NULL,
CODPROV	char(5) NOT NULL,
ESTCOM	char(1) NOT NULL,
);

--TABLE COMPRADETALLE
create table COMPRADETALLE (
IDCOMDET	int	IDENTITY(1, 1) NOT NULL,
CODCOM		char(5)NOT NULL,
CODPRO		char(5)NOT NULL,
CANPRO		int NOT NULL,
);


--RELECIONAL CLIENTE con CLIENTE_VENTA
ALTER TABLE CLIENTE ADD CONSTRAINT  CLIENTE_VENTA
	FOREIGN KEY (CDCLI)
	REFERENCES	CLIENTE (CODCLI);

--RELECIONAL VENDEDOR con VENDEDOR_VENTA
ALTER TABLE VENDEDOR ADD CONSTRAINT  VENDEDOR_VENTA
	FOREIGN KEY (CONVEND)
	REFERENCES	VENDEDOR (CONVEND);

--RELECIONAL VENDEDOR con VENDEDOR_COMPRA
ALTER TABLE VENDEDOR ADD CONSTRAINT  VENDEDOR_COMPRA
	FOREIGN KEY (CODVEND)
	REFERENCES	VENDEDOR(CODVEND);

--RELECIONAL PROVEEDOR con PROVEEDOR_COMPRA
ALTER TABLE PROVEEDOR ADD CONSTRAINT  PROVEEDOR_COMPRA
	FOREIGN KEY (CODPROV)
	REFERENCES	PROVEEDOR(CODPROV)

--RELECIONAL COMPRA con COMPRA_COMPRADETALLE
ALTER TABLE COMPRA ADD CONSTRAINT  COMPRA_CPOMPRADETALLE
	FOREIGN KEY (CODCOM)
	REFERENCES COMPRA(CODCOM)

--RELECIONAL PRODUCTO con PRODUCTO_COMPRADETALLE
ALTER TABLE PRODUCTO ADD CONSTRAINT  PRODUCTO_COMPRADETALLE
		FOREIGN KEY (IDCOMDET)
		REFERENCES PRODUCTO(IDCOMDET)
--RELECIONAL PRODUCTO con PRODUCTO_VENTADETALLE
ALTER TABLE PRODUCTO ADD CONSTRAINT  PRODUCTO_VENTADETALLE
		FOREIGN KEY (CODPRO)
		REFERENCES	PRODUCTO (CODPRO)

--